config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about"
  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  attachment :profile_image
  
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true

  validates :introduction, length: { maximum: 50 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
  
end
Refile.secret_key = '7db173ed4e10f2eaf3cf04e1d6ef789670fbbe76c701e672c26b32f6104d486eb166bcece96baf5ef4555a8e63fffce3b28da49be6361b8f8ccf31d0c6374cce'

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, {only:[:edit, :update, :destroy]}

  def ensure_correct_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
    redirect_to books_path
    end
  end

  def index
    @books = Book.all
    @newbook = Book.new
    @user = current_user
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
		@book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully"
      redirect_to book_path(@book.id)
    else
      @books= Book.all
      @user = current_user
      @newbook = Book.new(book_params)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end



  def show
	  @book = Book.find(params[:id])
    @newbook = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find_by(id: params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] = "Book was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, {only:[:edit, :update]}
  
  def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
    redirect_to user_path(current_user.id)
    end
  end
  
  def index
    @users = User.all
    @newbook = Book.new
    @user = current_user
  end
  
  def new
    @book = Book.new(book_params)
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    
    if @book.save
      redirect_to users_path,flash[:notice] = "You have created book successfully"
    else
      @books= Book.all
      @user = current_user
      @newbook = Book.new(book_params)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @newbook = Book.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	if @user.save
  		redirect_to user_path(@user.id)
      flash[:notice] = "Profile was successfully updated."
  	else
  		render :edit
  	end
  end
  
  
  
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% flash.each do |message_type, message| %>
    <%= message %>
<% end %>

<h1>Editing Book</h1>
<%if @book.errors.any? %>
<h3><%="#{@book.errors.full_messages.count} errors prohibited this obj being saved:" %></h3>
<%end%>

<% @book.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>

<%= form_with model:@book, local:true do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <br><%= f.submit 'Update Book' %>
<% end %>

<td><%= link_to "Show", book_path(@book.id) %><td>
|
<a href = "/books">Back</a>

app/views/books/index.html.erb
<main>
  <% flash.each do |message_type, message| %>
    <%= message %>
  <% end %>

  <%if @book.errors.any? %>
    <h3><%="#{@book.errors.full_messages.count} errors prohibited this obj being saved:" %></h3>
  <%end%>
    
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>

  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render partial: 'layouts/sidebar', locals:{ user: @user, newbook: @newbook } %>


      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <% flash.each do |message_type, message| %>
    <%= message %>
  <% end %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render partial: 'layouts/sidebar', locals:{ user: @user, newbook: @newbook } %>

      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %><br>
                <%= "#{@user.name}" %>
                <%end%>
              </td>
              <td><p class = "book-title"><%= link_to "#{@book.title}",book_path(@book.id) %></p></td>
              <td><%= @book.body%></td>
              <% if @book.user_id == current_user.id %>
    				  <td>
    				  	<%= link_to edit_book_path do %>
    				  	<button type="button" class="btn btn-success btn-sm">Edit</button>
    				  	<%end%>
    				  </td>
    				  <td>
    					  <%= link_to book_path, method: :delete, data: { confirm: '削除しますか？' } do %>
    					  <button type="button" class="btn btn-danger btn-sm">Destroy</button>
    				  	<%end%>
    				  </td>
    					<% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <% flash.each do |message_type, message| %>
    <%= message %>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
    				<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>
      </div>
    </div>
</div>
</main>

app/views/layouts/_sidebar.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody><tr></tr>
      <tr>
    	  <th>name</th>
    	  <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <%= link_to "", edit_user_path(user.id), :class => "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model:newbook, local:true do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class:"form-control book_title" %>
    </div>
    <div class="form-group">
      <label for="book_body">Body</label>
      <%= f.text_area :body, class:"form-control book_body"%>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to 'Bookers', root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li><%= link_to ' Home', user_path(current_user.id), class: "fas fa-home nav-link text-light" %></li>
                <li><%= link_to ' Users', users_path, class: "fas fa-users nav-link text-light" %></li>
                <li><%= link_to ' Books', books_path, class: "fas fa-book-open nav-link text-light" %></li>
                <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %></li>
              <% else %>
                <li><%= link_to " Home", root_path, class: "fas fa-home nav-link text-light" %></li>
                <li><%= link_to " About", home_about_path, class: "fas fa-link nav-link text-light" %></li>
                <li><%= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %></li>
                <li><%= link_to " login", user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>

    <footer>
      <div class="container mt-5">
      	<div class="row">
        	<div class="mx-auto">
        		<p>CopyRight Infratop.inc</p>
        	</div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<main>
  <% flash.each do |message_type, message| %>
    <%= message %>
  <% end %>
  
  <%if @user.errors.any? %>
  <h3><%="#{@user.errors.full_messages.count} errors prohibited this obj being saved:" %></h3>
  <%end%>
  
  <% @user.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
  
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name , class: "form-control" %>
        </div>
       <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <% flash.each do |message_type, message| %>
    <%= message %>
  <% end %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render partial: 'layouts/sidebar', locals:{ user: @user, newbook: @newbook } %>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                </td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <% flash.each do |message_type, message| %>
      <%= message %>
  <% end %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render partial: 'layouts/sidebar', locals:{ user: @user, newbook: @newbook } %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                  <%end%>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>